{
  "FILE_META": {
    "enum_name": "DiagnosticId",
    "enum_type": "uint16_t",
    "generate_string_map": "K_DIAGNOSTIC_ID_STRING_MAP"
  },
  "generic": {
    "unknown": {
      "name": "Unknown",
      "details": "The error is unknown.",
      "value": "0xF000"
    },
    "info": {
      "name": "info",
      "details": "Not and error, just info.",
      "value": "0xF001"
    },
    "debug": {
      "name": "debug",
      "details": "Not and error, just debug info.",
      "value": "0xF002"
    },
    "not_implemented": {
      "name": "Not Implemented",
      "details": "This feature is not implemented.",
      "value": "0xF003"
    },
    "home_env_var_not_set": {
      "name": "Home Environment Variable Not Set",
      "details": "The HOME environment variable is not set.",
      "value": "0xF004"
    },
    "home_env_var_not_dir": {
      "name": "Home Environment Variable Not Directory",
      "details": "The HOME environment variable is not a directory.",
      "value": "0xF005"
    },
    "failed_to_create_giraffe_dir": {
      "name": "Failed to Create Giraffe Directory",
      "details": "The giraffe directory could not be created.",
      "value": "0xF006"
    },
    "failed_to_create_gfs_image_dir": {
      "name": "Failed to Create GFS Image Directory",
      "details": "The GFS image directory could not be created.",
      "value": "0xF007"
    },
    "failed_to_create_gfs_log_dir": {
      "name": "Failed to Create GFS Log Directory",
      "details": "The GFS log directory could not be created.",
      "value": "0xF008"
    },
    "failed_to_create_gfs_data_dir": {
      "name": "Failed to Create GFS Data Directory",
      "details": "The GFS data directory could not be created.",
      "value": "0xF009"
    }
  },
  "config": {
    "section_not_found": {
      "name": "Section not found",
      "details": "The section was not found in the config file.",
      "value": "0x000E"
    },
    "setting_not_found": {
      "name": "Setting not found",
      "details": "The setting was not found in the config file.",
      "value": "0x0001"
    },
    "invalid_json_type": {
      "name": "Invalid JSON type",
      "details": "The type of the JSON value is not the expected type.",
      "value": "0x0002"
    },
    "invalid_setting_value": {
      "name": "Invalid setting value",
      "details": "The value of the setting is not valid.",
      "value": "0x0003"
    },
    "enum_not_string": {
      "name": "Enum value is not a string",
      "details": "The value of the enum is not a string.",
      "value": "0x0004"
    },
    "key_not_found_in_enum": {
      "name": "Key not found in enum",
      "details": "The key was not found in the enum.",
      "value": "0x0005"
    },
    "failed_to_save_to_path": {
      "name": "Failed to save to path",
      "details": "The config file could not be saved to the path.",
      "value": "0x0006"
    },
    "failed_to_open_config": {
      "name": "Failed to open config",
      "details": "The config file could not be opened.",
      "value": "0x0007"
    },
    "config_file_does_not_exist": {
      "name": "Config file does not exist",
      "details": "The config file does not exist.",
      "value": "0x0008"
    },
    "failed_to_load_section_not_found": {
      "name": "Failed to load config, section not found",
      "details": "A section of the config file could not be loaded because it was not found.",
      "value": "0x0009"
    },
    "extensions_not_array": {
      "name": "Extensions in config file is not an array",
      "details": "The extensions field in the config file must be an array, could not load any extensions.",
      "value": "0x000A"
    },
    "extension_not_object": {
      "name": "Extension is not an object",
      "details": "An item in the extensions array is not an object. This is reported along with the index of the item.",
      "value": "0x000B"
    },
    "extension_name_already_exists": {
      "name": "Extension Name Already Exists",
      "details": "This will happen during the loading or when adding an extension. Extension names must be unique.",
      "value": "0x000C"
    },
    "extension_name_does_not_exist": {
      "name": "Extension Name Does Not Exist",
      "details": "This will happen when trying to remove/alter an extension that does not exist.",
      "value": "0x000D"
    },
    "adc_mappings_not_array": {
      "name": "ADC Mappings Not Array",
      "details": "The ADC mappings field in the config file must be an array, could not load any ADC mappings.",
      "value": "0x000F"
    },
    "adc_mapping_not_object": {
      "name": "ADC Mapping Not Object",
      "details": "An item in the ADC mappings array is not an object. This is reported along with the index of the item.",
      "value": "0x0010"
    },
    "adc_mapping_label_already_exists": {
      "name": "ADC Mapping Label Already Exists",
      "details": "This will happen during the loading or when adding an ADC mapping. ADC mapping labels must be unique.",
      "value": "0x0011"
    }
  },
  "module": {
    "start_failure": {
      "name": "Failed to start module",
      "details": "A module failed to start",
      "value": "0x1000"
    },
    "module_already_started": {
      "name": "Module already started",
      "details": "A module was started twice",
      "value": "0x1001"
    }
  },
  "data_module": {
    "status_data_packet_unknown_source": {
      "name": "Unknown data packet source",
      "details": "The data packet source is not known to the data module",
      "value": "0x2000"
    },
    "data_packet_unknown_type": {
      "name": "Unknown data packet type",
      "details": "The data packet type is not known to the data module",
      "value": "0x2001"
    },
    "camera_new_image_packet_invalid_path": {
      "name": "Camera New Image Packet - Invalid Path",
      "details": "The path to the image is invalid.",
      "value": "0x2002"
    },
    "camera_new_image_packet_invalid_fields": {
      "name": "Camera New Image Packet - Invalid Fields",
      "details": "Error info contains the fields that are invalid. These packets must come from an extension.",
      "value": "0x2003"
    },
    "unrecognized_command": {
      "name": "Unrecognized Command",
      "details": "The command is not recognized by the data module.",
      "value": "0x2004"
    },
    "no_gps_source": {
      "name": "No GPS Source",
      "details": "No source for GPS data has been set.",
      "value": "0x2005"
    },
    "adc_interpolation_unknown_source": {
      "name": "ADC Interpolation Unknown Source",
      "details": "There is a source of ADC data that is not configured in the ADC channel map config. It will be reported as a raw count.",
      "value": "0x2006"
    }
  },
  "data_log": {
    "invalid_dataframe_strategy": {
      "name": "Invalid data log strategy",
      "details": "It should not be possible for this to happen. The strategy will revert to 'interval' and the whole dataframe will be logged.",
      "value": "0x3000"
    },
    "archive_old_data_files": {
      "name": "Failed to archive old data files",
      "details": "On startup, the data log module will attempt to archive old data files that are sitting in the data directory. This error is thrown if the archive fails.",
      "value": "0x3001"
    },
    "archive_old_log_files": {
      "name": "Failed to archive old log files",
      "details": "On startup, the data log module will attempt to archive old log files that are sitting in the log directory. This error is thrown if the archive fails.",
      "value": "0x3002"
    },

    "create_data_dir_bstrst": {
      "name": "Failed to create data directory at startup (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to create the data directory at startup.",
      "value": "0x3003"
    },
    "create_data_dir_stdexcept": {
      "name": "Failed to create data directory at startup (std::exception)",
      "details": "std::exception thrown when attempting to create the data directory at startup.",
      "value": "0x3004"
    },
    "data_dir_does_not_exist": {
      "name": "Data directory does not exist - after startup",
      "details": "The data directory does not exist after startup. This is a fatal error.",
      "value": "0x3005"
    },
    "data_dir_existence_bstrst": {
      "name": "Failed to check data directory existence (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to check the data directory existence.",
      "value": "0x3006"
    },
    "data_dir_existence_stdexcept": {
      "name": "Failed to check data directory existence (std::exception)",
      "details": "std::exception thrown when attempting to check the data directory existence.",
      "value": "0x3007"
    },
    "data_dir_create_failed": {
      "name": "Failed after reaching max attempts to create data directory",
      "details": "The data directory could not be created.",
      "value": "0x3008"
    },
    "create_data_archive_dir_bstrst": {
      "name": "Failed to create data archive directory at startup (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to create the data archive directory at startup.",
      "value": "0x3009"
    },
    "create_data_archive_dir_stdexcept": {
      "name": "Failed to create data archive directory at startup (std::exception)",
      "details": "std::exception thrown when attempting to create the data archive directory at startup.",
      "value": "0x300A"
    },
    "data_archive_dir_does_not_exist": {
      "name": "Data archive directory does not exist - after startup",
      "details": "The data archive directory does not exist after startup. This is a fatal error.",
      "value": "0x300B"
    },
    "data_archive_dir_existence_bstrst": {
      "name": "Failed to check data archive directory existence (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to check the data archive directory existence.",
      "value": "0x300C"
    },
    "data_archive_dir_existence_stdexcept": {
      "name": "Failed to check data archive directory existence (std::exception)",
      "details": "std::exception thrown when attempting to check the data archive directory existence.",
      "value": "0x300D"
    },
    "data_archive_dir_create_failed": {
      "name": "Failed after reaching max attempts to create data archive directory",
      "details": "The data archive directory could not be created.",
      "value": "0x300E"
    },
    "create_log_dir_bstrst": {
      "name": "Failed to create log directory at startup (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to create the log directory at startup.",
      "value": "0x300F"
    },
    "create_log_dir_stdexcept": {
      "name": "Failed to create log directory at startup (std::exception)",
      "details": "std::exception thrown when attempting to create the log directory at startup.",
      "value": "0x3010"
    },
    "log_dir_does_not_exist": {
      "name": "Data directory does not exist - after startup",
      "details": "The log directory does not exist after startup.",
      "value": "0x3011"
    },
    "log_dir_existence_bstrst": {
      "name": "Failed to check log directory existence (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to check the log directory existence.",
      "value": "0x3012"
    },
    "log_dir_existence_stdexcept": {
      "name": "Failed to check log directory existence (std::exception)",
      "details": "std::exception thrown when attempting to check the log directory existence.",
      "value": "0x3013"
    },
    "log_dir_create_failed": {
      "name": "Failed after reaching max attempts to create log directory",
      "details": "The log directory could not be created.",
      "value": "0x3014"
    },
    "create_log_archive_dir_bstrst": {
      "name": "Failed to create log archive directory at startup (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to create the log archive directory at startup.",
      "value": "0x3015"
    },
    "create_log_archive_dir_stdexcept": {
      "name": "Failed to create log archive directory at startup (std::exception)",
      "details": "std::exception thrown when attempting to create the log archive directory at startup.",
      "value": "0x3016"
    },
    "log_archive_dir_does_not_exist": {
      "name": "Data archive directory does not exist - after startup",
      "details": "The log archive directory does not exist after startup.",
      "value": "0x3017"
    },
    "log_archive_dir_existence_bstrst": {
      "name": "Failed to check log directory existence (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to check the log archive directory existence.",
      "value": "0x3018"
    },
    "log_archive_dir_existence_stdexcept": {
      "name": "Failed to check log archive directory existence (std::exception)",
      "details": "std::exception thrown when attempting to check the log archive directory existence.",
      "value": "0x3019"
    },
    "log_archive_dir_create_failed": {
      "name": "Failed after reaching max attempts to create log directory",
      "details": "The log archive directory could not be created.",
      "value": "0x301A"
    },
    "create_new_data_file_bstrst": {
      "name": "Failed to create new data file (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to create a new data file.",
      "value": "0x301B"
    },
    "create_new_data_file_stdexcept": {
      "name": "Failed to create new data file (std::exception)",
      "details": "std::exception thrown when attempting to create a new data file.",
      "value": "0x301C"
    },
    "create_new_log_file_bstrst": {
      "name": "Failed to create new log file (BoosterSeat errno)",
      "details": "BoosterSeat exception thrown when attempting to create a new log file.",
      "value": "0x301D"
    },
    "create_new_log_file_stdexcept": {
      "name": "Failed to create new log file (std::exception)",
      "details": "std::exception thrown when attempting to create a new log file.",
      "value": "0x301E"
    },
    "append_to_data_file": {
      "name": "Failed to append data to file",
      "details": "The data could not be appended to the data file.",
      "value": "0x301F"
    },
    "append_to_log_file": {
      "name": "Failed to append data to file",
      "details": "The data could not be appended to the log file.",
      "value": "0x3020"
    },
    "data_file_size_read": {
      "name": "Failed to read data file size",
      "details": "The data file size could not be read.",
      "value": "0x3021"
    },
    "log_file_size_read": {
      "name": "Failed to read log file size",
      "details": "The log file size could not be read.",
      "value": "0x3022"
    },
    "data_archive_dir_size_read": {
      "name": "Failed to read data archive directory size",
      "details": "The data archive directory size could not be read.",
      "value": "0x3023"
    },
    "log_archive_dir_size_read": {
      "name": "Failed to read log archive directory size",
      "details": "The log archive directory size could not be read.",
      "value": "0x3024"
    },
    "archive_data_file": {
      "name": "Failed to archive data file",
      "details": "The data file could not be archived.",
      "value": "0x3025"
    },
    "archive_log_file": {
      "name": "Failed to archive log file",
      "details": "The log file could not be archived.",
      "value": "0x3026"
    },
    "rotate_data_file": {
      "name": "Failed to rotate data file",
      "details": "The data file could not be rotated.",
      "value": "0x3027"
    },
    "rotate_log_file": {
      "name": "Failed to rotate log file",
      "details": "The log file could not be rotated.",
      "value": "0x3028"
    },
    "file_list_fail": {
      "name": "Failed to update archive file list",
      "details": "The archive file list could not be generated due to an exception.",
      "value": "0x3029"
    },
    "data_archive_trimmed": {
      "name": "Data Archive Trimmed",
      "details": "The data archive directory ran out of space and a file was deleted.",
      "value": "0x2004"
    },
    "data_archive_trim_failed": {
      "name": "Data Archive Trim Failed",
      "details": "The data archive directory is out of space, but a file could not be deleted.",
      "value": "0x302A"
    }
  },
  "console_module": {},
  "system_module": {
    "system_info_read_fail": {
      "name": "Failed to read system info",
      "details": "The system info could not be read in the system module",
      "value": "0x4001"
    },
    "cpu_temp_read_fail": {
      "name": "Failed to read CPU temperature",
      "details": "The CPU temperature could not be read in the system module",
      "value": "0x4002"
    },
    "disk_info_read_fail": {
      "name": "Failed to read disk info",
      "details": "The disk info could not be read in the system module",
      "value": "0x4003"
    }
  },
  "server_module": {
    "invalid_command_string": {
      "name": "Invalid Command String",
      "details": "Command string sent to the server module via a set request could not be parsed.",
      "value": "0x4100"
    }
  },
  "extension_module": {
    "failed_to_create": {
      "name": "Failed to Create Extension",
      "details": "The extension could not be created.",
      "value": "0x4004"
    },
    "invalid_command": {
      "name": "Invalid Command",
      "details": "The command sent to the extension module is not valid.",
      "value": "0x4005"
    },
    "invalid_preconfigured_extension_type": {
      "name": "Invalid Preconfigured Extension Type",
      "details": "The preconfigured extension type is not valid.",
      "value": "0x4006"
    },
    "failed_to_find_extension": {
      "name": "Failed to Find Extension",
      "details": "The extension from the previous command could not be found.",
      "value": "0x4007"
    }
  },
  "extension": {
    "start_call": {
      "name": "Can not start if already running, starting, or sleeping.",
      "details": "This case should not happen, but it can happen on a call to start.",
      "value": "0x5001"
    },
    "stop_timeout": {
      "name": "Failed to stop in time",
      "details": "The extension failed to stop in the time allotted.",
      "value": "0x5002"
    },
    "bme280_temperature_range": {
      "name": "BME280 Temperature Range Warning",
      "details": "The temperature is outside of the BME280's accurate range.",
      "value": "0x5003"
    },
    "bme280_pressure_range": {
      "name": "BME280 Pressure Range Warning",
      "details": "The pressure is outside of the BME280's accurate range.",
      "value": "0x5004"
    },
    "bme280_humidity_range": {
      "name": "BME280 Humidity Range Warning",
      "details": "The humidity is outside of the BME280's accurate range.",
      "value": "0x5005"
    },
    "bme280_div0": {
      "name": "BME280 DIV0",
      "details": "Prevented a DIV0 while processing BME280 data.",
      "value": "0x5006"
    },
    "ds18b20_temperature_range": {
      "name": "DS18B20 Temperature Range Warning",
      "details": "The temperature value read from the DS18B20 is outside of it's accurate range.",
      "value": "0x5007"
    },
    "samm8q_read_watchdog": {
      "name": "SAMM8Q Read Watchdog",
      "details": "The SAMM8Q read watchdog has expired.",
      "value": "0x5008"
    },
    "samm8q_configure_set_protocol": {
      "name": "SAMM8Q Configure Set Protocol",
      "details": "The SAMM8Q failed to set the protocol.",
      "value": "0x5009"
    },
    "samm8q_configure_set_measurement_rate": {
      "name": "SAMM8Q Configure Set Measurement Rate",
      "details": "The SAMM8Q failed to set the measurement rate.",
      "value": "0x500A"
    },
    "samm8q_configure_set_dynamic_model": {
      "name": "SAMM8Q Configure Set Dynamic Model",
      "details": "The SAMM8Q failed to set the dynamic model.",
      "value": "0x500B"
    },
    "samm8q_read_timeout": {
      "name": "SAMM8Q Read Timeout",
      "details": "The SAM-M8Q extension failed to read a frame in time.",
      "value": "0x500C"
    },
    "adc_config_fail": {
      "name": "ADC Config Failure",
      "details": "The ADC configuration string is invalid, defaulting to raw ADC count output",
      "value": "0x500D"
    },
    "camera_capture_fail": {
      "name": "Pi Camera Capture Failure",
      "details": "The Pi Camera extension failed to capture an image.",
      "value": "0x500E"
    },
    "samm8q_invalid_time": {
      "name": "SAMM8Q Invalid Time",
      "details": "The SAM-M8Q extension failed upon trying to convert the time into a C++ time object.",
      "value": "0x500F"
    }
  },
  "flight_runner": {
    "failed_to_route_command": {
      "name": "Failed to route command",
      "details": "The command could not be added to the respective module's command queue. This could be because the module is not running.",
      "value": "0x6000"
    },
    "command_destination_not_found": {
      "name": "Command destination not found",
      "details": "The command destination was not found.",
      "value": "0x6001"
    },
    "invalid_command": {
      "name": "Invalid Command",
      "details": "The command sent to the flight runner is not valid.",
      "value": "0x6002"
    },
    "launch_position_invalid": {
      "name": "Launch Position Invalid",
      "details": "The last gps fix was not valid when transitioning from pre-launch to launch.",
      "value": "0x6003"
    },
    "flight_phase_unknown": {
      "name": "Flight Phase Unknown",
      "details": "The flight phase manager no longer recognizes the current flight phase.",
      "value": "0x6004"
    },
    "phase_change_invalid": {
      "name": "Phase Change Invalid",
      "details": "Requested phase change is invalid.",
      "value": "0x6005"
    },
    "phase_change_unexpected": {
      "name": "Phase Change Unexpected",
      "details": "The phase change was not expected.",
      "value": "0x6006"
    },
    "failed_to_set_launch": {
      "name": "Failed to Set Launch",
      "details": "The system was unable to go into the launch phase. This could be because the system was not in the pre-launch phase or because the launch position could not be set (no GPS data).",
      "value": "0x6007"
    },
    "forced_recovery": {
      "name": "Forced Recovery",
      "details": "The system was forced into the recovery phase due to an error.",
      "value": "0x6008"
    },
    "bit_test_failed": {
      "name": "BIT Test Failed",
      "details": "The system failed the BIT test. See the error message for more details.",
      "value": "0x6009"
    },
    "bit_test_timeout": {
      "name": "BIT Test Timeout",
      "details": "The system timed out while running the BIT test. See the error message for more details.",
      "value": "0x600A"
    },
    "bit_test_start_failure": {
      "name": "BIT Test Start Failure",
      "details": "The system failed to start the BIT test. See the error message for more details.",
      "value": "0x600B"
    },
    "bit_test_stop_reset_failure": {
      "name": "BIT Test Stop or Reset Failure",
      "details": "The system failed to stop or reset the BIT test. See the error message for more details.",
      "value": "0x600C"
    },
    "bit_test_reset_failure": {
      "name": "BIT Test Reset Failure",
      "details": "The system failed to reset the BIT test. See the error message for more details.",
      "value": "0x600D"
    }
  },
  "ext_fault": {
    "none": {
      "name": "No fault",
      "details": "Default, should not be thrown.",
      "value": "0x7000"
    },
    "fatal_config": {
      "name": "Fatal Configuration Error",
      "details": "The extension has a fatal configuration error, it will not be restarted.",
      "value": "0x7001"
    },
    "bme280_startup_i2c_connect": {
      "name": "BME280 Startup I2C Connect Fault",
      "details": "The extension failed to connect to the I2C bus on startup.",
      "value": "0x7002"
    },
    "bme280_startup_handshake": {
      "name": "BME280 Startup Handshake Fault",
      "details": "The BME280 failed to handshake on startup after a set number of retry attempt.",
      "value": "0x7003"
    },
    "bme280_startup_configure": {
      "name": "BME280 Startup Configure Fault",
      "details": "Failed to configure the BME280 on startup.",
      "value": "0x7003"
    },
    "bme280_startup_read_compensation": {
      "name": "BME280 Startup Read Compensation Fault",
      "details": "Failed to read compensation data from the BME280 on startup.",
      "value": "0x7003"
    },
    "bme280_read_timeout": {
      "name": "BME280 Read Timeout Fault",
      "details": "While running, the BME280 failed to successfully read good data from the sensor before the timeout.",
      "value": "0x7004"
    },
    "ds18b20_id_invalid": {
      "name": "DS18B20 Invalid ID Fault",
      "details": "The configured DS18B20 ID does not match the regex pattern.",
      "value": "0x7005"
    },
    "ds18b20_device_not_found": {
      "name": "DS18B20 Device Not Found Fault",
      "details": "The configured DS18B20 ID was not found on the bus.",
      "value": "0x7006"
    },
    "ds18b20_read_raw": {
      "name": "DS18B20 Timeout - Read Raw",
      "details": "The DS18B20 timed out, it's last failure was while trying to read raw data.",
      "value": "0x7007"
    },
    "ds18b20_raw_temp_empty": {
      "name": "DS18B20 Timeout - Raw Temp Empty",
      "details": "The DS18B20 timed out, it's last failure was having an empty raw temperature value.",
      "value": "0x7008"
    },
    "ds18b20_raw_temp_stoi": {
      "name": "DS18B20 Timeout - STOI",
      "details": "The DS18B20 timed out, it's last failure was on trying to convert the raw temperature string to a integer.",
      "value": "0x7009"
    },
    "ds18b20_init_timeout": {
      "name": "DS18B20 Timeout - Init",
      "details": "The DS18B20 timed out on initialization but did not provide a more specific error. This should not happen.",
      "value": "0x700A"
    },
    "ds18b20_read_timeout": {
      "name": "DS18B20 Timeout - Read",
      "details": "The DS18B20 timed out on read but did not provide a more specific error. This should not happen.",
      "value": "0x700B"
    },
    "samm8q_i2c_connect": {
      "name": "SAMM8Q I2C Connect Fault",
      "details": "The SAMM8Q extension failed to connect to the I2C bus.",
      "value": "0x700C"
    },
    "samm8q_startup_handshake": {
      "name": "SAMM8Q Startup Handshake Fault",
      "details": "The SAMM8Q extension failed to handshake in time.",
      "value": "0x700D"
    },
    "samm8q_reset_failure": {
      "name": "SAMM8Q Reset Failure Fault",
      "details": "The SAMM8Q extension failed to reset in time.",
      "value": "0x700E"
    },
    "i2c_bus_connect_fault": {
      "name": "I2C Bus Connect Fault",
      "details": "The I2C bus failed to connect. Does it exist and is it enabled?",
      "value": "0x700F"
    },
    "i2c_address_set_fault": {
      "name": "I2C Address Set Fault",
      "details": "The I2C address failed to set.",
      "value": "0x7010"
    },
    "i2c_unknown_fault": {
      "name": "I2C Unknown Fault",
      "details": "The I2C bus failed for an unknown reason.",
      "value": "0x7011"
    },
    "i2c_handshake_timeout_fault": {
      "name": "I2C Handshake Timeout Fault",
      "details": "The I2C handshake timed out.",
      "value": "0x7012"
    },
    "adc_watchdog_timeout": {
      "name": "ADC Watchdog Timeout Fault",
      "details": "The ADC did not successfully read a value before the watchdog timer expired.",
      "value": "0x7013"
    },
    "bmi088_address_error": {
      "name": "Provided BMI088 address is invalid",
      "details": "Extra args should be provided with the format: \"<accel_address>,<gyro_address>\"",
      "value": "0x7014"
    },
    "bmi088_accel_handshake_error": {
      "name": "BMI088 Accel Handshake Error",
      "details": "The BMI088 Accelerometer failed to handshake.",
      "value": "0x7015"
    },
    "bmi088_gyro_handshake_error": {
      "name": "BMI088 Gyro Handshake Error",
      "details": "The BMI088 Gyroscope failed to handshake.",
      "value": "0x7016"
    },
    "bmi088_accel_open_error": {
      "name": "BMI088 Accel Open Error",
      "details": "The BMI088 Accelerometer SPI path failed to open.",
      "value": "0x7017"
    },
    "bmi088_gyro_open_error": {
      "name": "BMI088 Gyro Open Error",
      "details": "The BMI088 Gyroscope SPI path failed to open.",
      "value": "0x7018"
    },
    "bmi088_accel_config_error": {
      "name": "BMI088 Accel Config Error",
      "details": "The BMI088 Accelerometer failed to configure.",
      "value": "0x7019"
    },
    "bmi088_gyro_config_error": {
      "name": "BMI088 Gyro Config Error",
      "details": "The BMI088 Gyroscope failed to configure.",
      "value": "0x701A"
    },
    "bmi088_read_timeout": {
      "name": "BMI088 Read Timeout",
      "details": "The BMI088 failed to read data in time.",
      "value": "0x701B"
    },
    "rgb_status_led_extra_args": {
      "name": "RGB Status LED Extra Args",
      "details": "The RGB status LED extension was provided invalid extra args. (GPIO Config)",
      "value": "0x701C"
    },
    "rgb_status_led_failed_to_setup_pins": {
      "name": "RGB Status LED Failed to Setup Pins",
      "details": "The RGB status LED extension failed to setup the GPIO pins.",
      "value": "0x701D"
    },
    "rgb_status_led_shutdown_failed": {
      "name": "RGB Status LED Shutdown Failed",
      "details": "The RGB status LED extension failed to shutdown.",
      "value": "0x701E"
    },
    "pi_camera_not_on_pi": {
      "name": "Pi Camera Not on Pi",
      "details": "The Pi Camera extension is not running on a Raspberry Pi.",
      "value": "0x701F"
    },
    "pi_camera_not_detected": {
      "name": "Pi Camera Not Detected",
      "details": "The Pi Camera extension failed to detect the camera.",
      "value": "0x7020"
    },
    "pi_camera_detect_failed": {
      "name": "Pi Camera Detect Failed",
      "details": "The Pi Camera extension ran into an error, possibly related to the rpicam-apps install.",
      "value": "0x7021"
    },
    "pi_camera_invalid_image_dir": {
      "name": "Pi Camera Invalid Image Directory",
      "details": "The Pi Camera extension was provided an invalid image directory.",
      "value": "0x7022"
    },
    "pi_camera_capture_failed": {
      "name": "Pi Camera Capture Failed (multiple)",
      "details": "The Pi Camera extension has failed multiple times to capture an image.",
      "value": "0x7023"
    },
    "imu_watchdog_timeout": {
      "name": "IMU Watchdog Timeout",
      "details": "The IMU extension failed to read data in time.",
      "value": "0x7024"
    },
    "imu_invalid_report_interval": {
      "name": "IMU Invalid Report Interval",
      "details": "The IMU extension was provided an invalid report interval in it's extra args.",
      "value": "0x7025"
    }
  },
  "interface": {
    "invalid_gpio_pin": {
      "name": "Invalid GPIO Pin",
      "details": "The GPIO pin is not valid.",
      "value": "0x8000"
    },
    "invalid_gpio_pin_mode": {
      "name": "Invalid GPIO Pin Mode",
      "details": "The GPIO pin mode is not valid.",
      "value": "0x8001"
    },
    "initial_state_input_pin": {
      "name": "Initial State Input Pin",
      "details": "The GPIO pin is an input pin and can not be set to an initial state.",
      "value": "0x8002"
    },
    "gpio_failed_to_init": {
      "name": "GPIO Init Failed",
      "details": "Failed to open /dev/gpiomem",
      "value": "0x8003"
    },
    "gpio_failed_to_map_registers": {
      "name": "GPIO Map Registers Failed",
      "details": "Failed to map registers",
      "value": "0x8004"
    },
    "gpio_not_initialized": {
      "name": "GPIO Not Initialized",
      "details": "A pin can not be reserved as the GPIO module has not been initialized.",
      "value": "0x8005"
    },
    "gpio_pin_already_reserved": {
      "name": "GPIO Pin Already Reserved",
      "details": "The GPIO pin is already reserved.",
      "value": "0x8006"
    },
    "gpio_not_owner": {
      "name": "GPIO Not Owner",
      "details": "The GPIO pin is not owned by the caller.",
      "value": "0x8007"
    },
    "gpio_pin_not_output": {
      "name": "GPIO Pin Not Output",
      "details": "The GPIO pin is not an output pin. Can't write to it.",
      "value": "0x8008"
    },
    "gpio_not_reserver_or_not_owner": {
      "name": "GPIO Pin Not Reserved or Not Owner",
      "details": "The GPIO pin is not reserved or the caller is not the owner.",
      "value": "0x8009"
    },
    "gpio_can_not_read_output_pin": {
      "name": "GPIO Can Not Read Output Pin",
      "details": "The GPIO pin is an output pin and can not be read.",
      "value": "0x800A"
    }
  },
  "gdl": {
    "invalid_start_call": {
      "name": "Invalid Start Call",
      "details": "Call to GDL::start() when not in the stopped state.",
      "value": "0xA000"
    },
    "invalid_stop_call": {
      "name": "Invalid Stop Call",
      "details": "Call to GDL::stop() when not in the running state.",
      "value": "0xA001"
    },
    "invalid_broadcast_call": {
      "name": "Invalid Broadcast Call",
      "details": "Call to GDL::broadcast() when not in the running state.",
      "value": "0xA002"
    },
    "invalid_exchange_call": {
      "name": "Invalid Exchange Call",
      "details": "Call to GDL::exchange() when not in the running state.",
      "value": "0xA003"
    }
  },
  "telemetry": {
    "invalid_command": {
      "name": "Invalid Command",
      "details": "The command sent to the telemetry module is not valid.",
      "value": "0xB000"
    },
    "mode_not_enabled": {
      "name": "Mode Not Enabled",
      "details": "The functionality requested is not enabled. (SSTV)",
      "value": "0xB001"
    },
    "sstv_error": {
      "name": "SSTV Error",
      "details": "An error occurred while trying to send an SSTV image. See info.",
      "value": "0xB002"
    },
    "radio_configuration": {
      "name": "Radio Configuration Error",
      "details": "The radio configuration is invalid.",
      "value": "0xB003"
    },
    "data_link_error": {
      "name": "Data Link Error",
      "details": "Error related to the data link.",
      "value": "0xB004"
    },
    "data_link_send_error": {
      "name": "Data Link Send Error",
      "details": "Error related to sending data over the data link.",
      "value": "0xB005"
    },
    "aprs_telemetry_initialization": {
      "name": "APRS Telemetry Initialization Error",
      "details": "Error related to initializing the APRS telemetry. See info.",
      "value": "0xB006"
    }
  }
}
